# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    # - name: Install pre requiriments
    #   run: sudo apt-get update && sudo apt-get install imagemagick tree
      
    - name: Build with Gradle Wrapper
      run: ./package.sh
      
    - name: Show production folder
      run: ls out/production/Microcraft/
      
    - name: View all repo
      run: tree .
      
    - name: loking for jar
      run: find . -name *Microcraft*.jar
    
    - uses: actions/upload-artifact@v4
      with:
        name: Microcraft.jar
        path: out/artifacts/Microcraft_jar/Microcraft.jar
        
    # - name: Download a Build Artifact
    #   uses: actions/download-artifact@v5.0.0
    #   with:
    #     # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
    #     name: Microcraft.jar
    #     path: out/artifacts/Microcraft_jar/Microcraft.jar
